# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Q49rVTlGYEFJfyE8QPhNSfI0T1teln0
"""

# Install Whisper and ffmpeg
!pip install -U openai-whisper
!apt-get install -y ffmpeg

import whisper
from google.colab import files

# Upload audio file
uploaded = files.upload()
audio_file = next(iter(uploaded))  # Get the uploaded file name

# Load Whisper model
model = whisper.load_model("base")  # You can change to "small" or "medium" for different speed/accuracy

# Transcribe the audio file
result = model.transcribe(audio_file)

# Print the transcription text
print("Transcription:")
print(result['text'])